### ISSUE TITLE
Cache Simulator - Parse config file

### ISSUE THREAD

**Issue by ghost** [brandiweekes/cpsc5041#1]
Write a function that correctly parses the config file. The function should accept as a param a string with the filename. The function should then create a struct of type Config (with the necessary properties), open the file,  and assign each config value to a Config property. Then it should return the Config.

**Comment by brandiweekes** [comment]
Resolved in: d7ec13da652c80bc12de03e746e24db1dcaeb206

includes debug output to verify content
