### ISSUE TITLE
Cache Simulator - Parse input file

### ISSUE THREAD

**Issue by ghost** [brandiweekes/cpsc5041#2]
Write a function that correctly parses the input file. The function should accept as a param a string with the filename. The function should then create a vector of type int (or binary or hex, whichever is easier), open the file, and insert each value into the vector. Then it should return the vector.

**Comment by brandiweekes** [comment]
Resolved in: d7ec13da652c80bc12de03e746e24db1dcaeb206

Includes debug output to verify file content
